/*
 * Pattern metadata: plain data, no React imports, so the build (vite.config.ts)
 * can read it to generate llms.txt, patterns.json and per-pattern docs.
 * Add a pattern = add an entry here + the file under src/patterns/.
 */
export const CATEGORIES = [
  'Foundations',
  'Components',
  'Text',
  'Motion',
  'Backgrounds',
  '3D',
  '3D Motion',
  'Layouts',
  'Sections',
  'Screens',
  'Data viz',
  'Recipes',
] as const

export type Category = (typeof CATEGORIES)[number]

export type PatternMeta = {
  slug: string
  title: string
  category: Category
  summary: string
  /** When to reach for this. Every entry needs at least one. */
  when: string[]
  /** Source file under src/patterns, shown in the code panel. */
  file: string
  source?: { label: string; url: string }
  /** Search keywords for humans and AI: technique names, use cases, look. */
  tags?: string[]
  /** Accessibility notes: keyboard, screen reader, reduced-motion behaviour. */
  a11y?: string
  /** Runtime deps beyond React + Tailwind. Empty = copy the file and go. */
  deps?: string[]
}

const ALL: PatternMeta[] = [
  {
    slug: 'tokens',
    tags: ["design tokens", "css variables", "theme", "dark mode", "color", "typography", "spacing"],
    a11y: "Colour pairs meet WCAG AA for body text in both themes. Motion durations collapse to 0 under prefers-reduced-motion.",
    title: 'Design tokens',
    category: 'Foundations',
    summary: 'Color, type, spacing, radius, elevation and motion tokens. Light/dark aware, no flash.',
    when: [
      'Starting any new project: copy src/tokens/tokens.css first',
      'Plain HTML projects too; the file has no framework dependency',
    ],
    file: 'foundations/Tokens.tsx',
  },
  {
    slug: 'buttons',
    tags: ["button", "cta", "loading", "variants"],
    a11y: "Native <button>; aria-busy while loading; disabled state removes pointer events; visible focus ring from tokens.",
    title: 'Buttons',
    category: 'Components',
    summary: 'Primary / secondary / ghost / danger, three sizes, loading state and a tactile press.',
    when: ['Any clickable action', 'Swap --accent to rebrand without touching the component'],
    file: 'components/Buttons.tsx',
  },
  {
    slug: 'scroll-reveal',
    tags: ["scroll animation", "reveal", "fade in", "animation-timeline", "css only"],
    a11y: "Content is visible without support (@supports guard). Animation removed under reduced motion.",
    title: 'Scroll reveal (CSS only)',
    category: 'Motion',
    summary: 'Elements fade and rise as they enter the viewport using animation-timeline: view(). Zero JS.',
    when: [
      'Landing pages and long-form sections',
      'Prefer this over IntersectionObserver when you only need enter animations',
    ],
    file: 'motion/ScrollReveal.tsx',
    source: {
      label: 'MDN: scroll-driven animations',
      url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll-driven_animations',
    },
  },
  {
    slug: 'view-transition-grid',
    tags: ["view transitions", "shared element", "page transition", "morph", "gallery"],
    a11y: "Plain buttons; without View Transitions support the swap is instant. Disable transitions for reduced motion globally.",
    title: 'Shared-element view transition',
    category: 'Motion',
    summary: 'A card morphs into its detail view with the View Transitions API. Falls back to an instant swap.',
    when: ['Grid → detail navigation', 'Gallery / product / project pages (MemoryShards-style)'],
    file: 'motion/ViewTransitionGrid.tsx',
    source: {
      label: 'MDN: View Transition API',
      url: 'https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API',
    },
  },
  {
    slug: 'count-up',
    tags: ["counter", "stats", "numbers", "kpi", "intersection observer"],
    a11y: "Final value shown immediately under reduced motion; tabular-nums avoids layout shift.",
    title: 'Count-up stats',
    category: 'Motion',
    summary: 'Numbers animate from 0 when scrolled into view, with tabular figures so width stays stable.',
    when: ['Stat tiles on landing pages and dashboards'],
    file: 'motion/CountUp.tsx',
    source: { label: 'For fancier digit rolls: number-flow', url: 'https://github.com/barvian/number-flow' },
  },
  {
    slug: 'command-palette',
    tags: ["cmdk", "search", "command menu", "keyboard", "dialog", "ctrl k"],
    a11y: "Native <dialog> traps focus and handles Esc; listbox/option roles with aria-selected; full keyboard nav.",
    title: 'Command palette',
    category: 'Components',
    summary: 'Ctrl/⌘K launcher on the native <dialog>: focus trap, Esc and backdrop for free, arrow-key navigation.',
    when: ['Any app with more than a handful of pages or actions', 'Power-user shortcut on top of normal nav, never instead of it'],
    file: 'components/CommandPalette.tsx',
    source: { label: 'Heavier alternative: cmdk', url: 'https://github.com/pacocoursey/cmdk' },
  },
  {
    slug: 'mesh-gradient',
    tags: ["gradient", "background", "blob", "hero", "grain", "css only"],
    a11y: "aria-hidden decorative layer; animation stops under reduced motion.",
    title: 'Animated mesh gradient',
    category: 'Backgrounds',
    summary: 'Three blurred blobs drifting on offset loops, plus SVG grain. Pure CSS hero background.',
    when: ['Hero and section backgrounds', 'Set --mesh-a/b/c to rebrand; pair with big display type'],
    file: 'recipes/MeshGradient.tsx',
    source: { label: 'Generator alternative: Mesh Gradient', url: 'https://www.meshgradient.com/' },
  },
  {
    slug: 'toast',
    tags: ["notification", "snackbar", "feedback", "alert"],
    a11y: "aria-live=\"polite\" region; dismiss buttons labelled.",
    title: 'Toasts',
    category: 'Components',
    summary: 'Provider + useToast() hook. Stacks up to four, auto-dismisses, springs in, announced via aria-live.',
    when: ['Confirming a background action (saved, sent, copied)', 'Never for errors the user must act on; use inline errors'],
    file: 'components/Toast.tsx',
    source: { label: 'Fuller alternative: Sonner', url: 'https://sonner.emilkowal.ski/' },
  },
  {
    slug: 'drawer',
    tags: ["sheet", "side panel", "dialog", "filters", "off-canvas"],
    a11y: "Native <dialog> modal: focus trap, Esc closes, background inert; close button labelled.",
    title: 'Drawer',
    category: 'Components',
    summary: 'Left or right sheet on the native <dialog>, with animated exit and backdrop fade.',
    when: ['Filters, settings, detail panes that keep list context', 'Mobile navigation'],
    file: 'components/Drawer.tsx',
  },
  {
    slug: 'spotlight-card',
    tags: ["hover effect", "glow", "tilt", "cursor", "card"],
    a11y: "Purely decorative on pointer; tilt disabled under reduced motion; content readable without effect.",
    title: 'Spotlight card',
    category: 'Motion',
    summary: 'Cursor-following glow and slight 3D tilt, driven by CSS variables so React never re-renders.',
    when: ['Feature grids and pricing cards on landing pages', 'Sparingly: one group per page'],
    file: 'motion/SpotlightCard.tsx',
  },
  {
    slug: 'bento-grid',
    tags: ["bento", "grid", "features", "layout", "dashboard summary"],
    a11y: "Source order = reading order; collapses to a single column.",
    title: 'Bento grid',
    category: 'Layouts',
    summary: 'Six-column grid with mixed tile spans and dense packing. Collapses to one column on phones.',
    when: ['Feature overviews and dashboard summaries', 'Landing sections that need hierarchy without a long list'],
    file: 'layouts/BentoGrid.tsx',
  },
  {
    slug: 'timeline',
    tags: ["timeline", "activity feed", "history", "events"],
    a11y: "Semantic <ol> + <time>; confidence also conveyed by legend, not colour alone.",
    title: 'Event timeline',
    category: 'Data viz',
    summary: 'Vertical rail with aligned mono timestamps and confidence-coloured dots. Rows reveal on scroll.',
    when: ['Activity feeds, audit logs, reconstructed days (MemoryShards)', 'Order and delivery tracking'],
    file: 'dataviz/Timeline.tsx',
  },
  {
    slug: 'marquee',
    tags: ["marquee", "ticker", "logo wall", "infinite scroll", "loop"],
    a11y: "Duplicate copy is aria-hidden; pauses on hover; static under reduced motion.",
    title: 'Infinite marquee',
    category: 'Recipes',
    summary: 'Seamless looping strip with faded edges, pause on hover, any speed and direction.',
    when: ['Logo walls, tech stacks, testimonials', 'Keep it decorative; nothing essential should scroll away'],
    file: 'recipes/Marquee.tsx',
  },
  {
    slug: "shader-background",
    title: "Shader backgrounds",
    category: "Backgrounds",
    summary: "One WebGL shader, seven looks (mesh, aurora, swirl, voronoi, flame, halftone, metal) and 16 palette presets with a print-like dither.",
    when: ["Hero and section backgrounds that need to feel alive", "Replace background videos: a few KB of GLSL instead of MBs of MP4", "Pick a preset, or pass your own 4-colour palette"],
    file: "backgrounds/ShaderBackground.tsx",
    tags: ["shader", "webgl", "glsl", "aurora", "flame", "voronoi", "halftone", "metal", "gradient", "background", "hero"],
    a11y: "Canvas is aria-hidden. Pauses off-screen and in hidden tabs; renders one still frame under reduced motion; CSS gradient fallback without WebGL.",
  },
  {
    slug: "dot-grid-warp",
    title: "Dot grid warp",
    category: "Backgrounds",
    summary: "A faint dot grid that bends toward the pointer like a rubber sheet under a weight. Canvas 2D, Gaussian falloff.",
    when: ["Interactive hero or section backgrounds", "Developer-tool and AI product pages"],
    file: "backgrounds/DotGridWarp.tsx",
    tags: ["canvas", "interactive background", "dots", "grid", "pointer", "gravity"],
    a11y: "Decorative, aria-hidden. Static grid under reduced motion; idles when the pointer leaves.",
  },
  {
    slug: "scramble-text",
    title: "Scramble text",
    category: "Text",
    summary: "Text decodes into place, characters cycling through glyphs and locking in left to right.",
    when: ["Intro taglines, nav labels, loading states", "Tech, studio and portfolio sites (Alche-style)"],
    file: "text/ScrambleText.tsx",
    tags: ["text effect", "decode", "glitch", "typewriter", "hacker", "intro"],
    a11y: "Final text exposed via aria-label; scrambling glyphs are aria-hidden; instant under reduced motion.",
  },
  {
    slug: "focus-reveal",
    title: "Focus reveal",
    category: "Text",
    summary: "Blurred words come sharp one at a time as a camera-style focus frame travels to each measured word box.",
    when: ["Hero headlines and manifesto lines", "Anywhere one phrase should be read word by word"],
    file: "text/FocusReveal.tsx",
    tags: ["text effect", "blur", "focus", "headline", "camera"],
    a11y: "Sentence exposed via aria-label; frame decorative; all words sharp and static under reduced motion.",
  },
  {
    slug: "blueprint-intro",
    title: "Blueprint intro",
    category: "Motion",
    summary: "Construction lines draw across the frame, then the logo traces itself, then the tagline fades in. SVG stroke animation.",
    when: ["Studio / architecture / engineering landing intros", "Loading screen that shows the brand being built"],
    file: "motion/BlueprintIntro.tsx",
    tags: ["intro", "loader", "svg", "line drawing", "stroke-dashoffset", "logo animation"],
    a11y: "role=\"img\" with a label; finished drawing shown immediately under reduced motion. Keep intros under ~3s and skippable.",
  },
  {
    slug: "pinned-horizontal",
    title: "Pinned horizontal scroll",
    category: "Motion",
    summary: "Vertical scroll drives a horizontal track inside a pinned (sticky) frame. No library.",
    when: ["Process steps, case-study galleries, timelines", "Storytelling sections on landing pages"],
    file: "motion/PinnedHorizontal.tsx",
    tags: ["scroll", "sticky", "pin", "horizontal scroll", "scrollytelling", "parallax"],
    a11y: "Falls back to a normal horizontally scrollable row under reduced motion; container is focusable for keyboard scrolling.",
  },
  {
    slug: "sound-opt-in",
    title: "Sound opt-in",
    category: "Components",
    summary: "Asks before playing sound with two equal choices, remembers the answer and leaves a small equaliser toggle.",
    when: ["Immersive sites with music or UI sounds", "Any autoplay-audio temptation"],
    file: "components/SoundOptIn.tsx",
    tags: ["audio", "consent", "sound toggle", "immersive"],
    a11y: "No audio without an explicit click; toggle uses aria-pressed; animation stops under reduced motion.",
  },
  {
    slug: "liquid-glass-button",
    title: "Liquid glass button",
    category: "Components",
    summary: "Glass pill: backdrop blur + saturate, bevel shadows, and a pointer-following highlight on registered CSS properties.",
    when: ["CTAs over imagery, video or shader backgrounds", "Apple-style glass UI"],
    file: "components/LiquidGlassButton.tsx",
    tags: ["glassmorphism", "liquid glass", "button", "backdrop-filter", "@property"],
    a11y: "Native button. Check text contrast against the actual background; transition removed under reduced motion.",
  },
  {
    slug: "expanding-cards",
    title: "Expanding cards",
    category: "Components",
    summary: "A rail of tall slivers; the active one widens into a full card. Caption laid out at final width so it never rewraps.",
    when: ["Destination / product / portfolio pickers", "Feature showcases with imagery"],
    file: "components/ExpandingCards.tsx",
    tags: ["accordion", "cards", "gallery", "hover expand", "flex-grow"],
    a11y: "Buttons with aria-expanded; activates on hover, focus and click so keyboard and touch work.",
  },
  {
    slug: "morph-pill-card",
    title: "Morph pill card",
    category: "Components",
    summary: "An avatar pill that grows into a full profile card: one surface animating between two sizes.",
    when: ["Team / author / creator previews", "Compact UI that reveals detail on intent"],
    file: "components/MorphPillCard.tsx",
    tags: ["morph", "hover card", "profile", "avatar", "expand"],
    a11y: "Focusable with aria-expanded; opens on focus and toggles with Enter/Space; hidden button removed from tab order when closed.",
  },
  {
    slug: "fan-deck",
    title: "Fan deck",
    category: "Components",
    summary: "A hand of cards splayed from one pivot below the deck; the focused card lifts out of the spread.",
    when: ["Services, steps, pricing plans, collectibles", "Playful portfolio sections"],
    file: "components/FanDeck.tsx",
    tags: ["cards", "fan", "deck", "rotate", "transform-origin"],
    a11y: "Each card is a button with aria-pressed; arrow keys move between cards.",
  },
  {
    slug: "ring-carousel",
    title: "3D ring carousel",
    category: "3D",
    summary: "Cards on a true CSS 3D cylinder; drag to spin with momentum, snaps to the nearest card.",
    when: ["Portfolio and product showcases", "Anywhere a gallery should feel physical"],
    file: "three-d/RingCarousel.tsx",
    tags: ["carousel", "3d", "css 3d", "drag", "momentum", "cylinder", "slider"],
    a11y: "Focusable region with aria-roledescription=\"carousel\", arrow keys rotate, label announces position; no coasting under reduced motion.",
  },
  {
    slug: "coverflow",
    title: "Depth coverflow",
    category: "3D",
    summary: "Coverflow where cards turn edge-on, sink and blur with distance from the active one. Plain CSS 3D.",
    when: ["Album / product / case-study browsers", "Hero galleries"],
    file: "three-d/Coverflow.tsx",
    tags: ["coverflow", "carousel", "3d", "depth", "slider"],
    a11y: "Prev/next buttons labelled, arrow keys, aria-live announces the active item.",
  },
  {
    slug: "particle-globe",
    title: "Particle globe",
    category: "3D",
    summary: "A sphere of points on a Fibonacci lattice with a noise land mask; drag to spin with momentum. Canvas 2D.",
    when: ["Global / network / logistics product heroes", "About pages showing reach"],
    file: "three-d/ParticleGlobe.tsx",
    tags: ["globe", "sphere", "particles", "canvas", "3d", "drag", "earth"],
    a11y: "role=\"img\" with label; pauses off-screen; no idle spin under reduced motion.",
  },
  {
    slug: "pricing-tiers",
    title: "Pricing tiers",
    category: "Sections",
    summary: "Three plans with a monthly/yearly radiogroup, featured middle card, tick lists and a ghost wordmark.",
    when: ["SaaS and product pricing pages"],
    file: "sections/PricingTiers.tsx",
    tags: ["pricing", "plans", "section", "billing toggle", "saas"],
    a11y: "Billing switch is a radiogroup with aria-checked; section labelled by its heading; ticks are aria-hidden.",
  },
  {
    slug: "wordmark-footer",
    title: "Wordmark footer",
    category: "Sections",
    summary: "Newsletter, link columns and a giant wordmark bleeding off the bottom edge, sized with container query units.",
    when: ["Studio, agency and brand sites", "Any footer that should close the page with presence"],
    file: "sections/WordmarkFooter.tsx",
    tags: ["footer", "wordmark", "newsletter", "container queries", "section"],
    a11y: "Labelled email input, nav landmarks per column; giant wordmark aria-hidden since the brand is in text.",
  },
  {
    slug: "contact-section",
    title: "Contact section",
    category: "Sections",
    summary: "Promise list, contact rows and a glass form with labelled fields, validation summary and success state.",
    when: ["Agency / freelancer / product contact pages"],
    file: "sections/ContactSection.tsx",
    tags: ["contact", "form", "validation", "section", "enquiry"],
    a11y: "Real <label>s, required fields, error summary in aria-live, success state with role=\"status\".",
  },
  {
    slug: "analytics-dashboard",
    title: "Analytics dashboard",
    category: "Screens",
    summary: "Full screen: sidebar, KPI tiles with sparklines, paired bar chart, arc dial, donut and orders table, all hand-drawn SVG.",
    when: ["Admin panels, SaaS dashboards, store analytics", "Reference for drawing charts without a library"],
    file: "screens/AnalyticsDashboard.tsx",
    tags: ["dashboard", "admin", "charts", "svg charts", "kpi", "table", "donut", "sparkline"],
    a11y: "Charts have role=\"img\" + text labels; data also present as text and a real <table> with scoped headers; aria-current on nav.",
  },
  {
    slug: "helix-gallery",
    title: "Helix gallery (spiral of pictures)",
    category: "3D",
    summary: "Images wound onto a helix that turns and climbs; far side dims and blurs. Drag to spin, idle rotation.",
    when: ["Portfolio / photography heroes", "Any gallery that should feel like an installation"],
    file: "three-d/HelixGallery.tsx",
    tags: ["spiral", "helix", "3d gallery", "images", "carousel", "css 3d", "drag"],
    a11y: "Focusable carousel region, arrow keys step, images decorative (alt=\"\"); idle spin stops under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "dna-carousel",
    title: "DNA double-helix carousel",
    category: "3D",
    summary: "Two opposing strands of pictures joined by rungs, drifting along the axis; depth from scale, blur and z-sort.",
    when: ["Biotech / science / data brands", "Playful image strips"],
    file: "three-d/DnaCarousel.tsx",
    tags: ["dna", "double helix", "3d", "carousel", "images", "drag"],
    a11y: "role=\"img\" with label; drag optional; idle drift stops under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "wave-gallery",
    title: "Wave gallery",
    category: "3D",
    summary: "An endless ribbon of cards bent into a depth wave; cards crest toward you and sink into fog. Drag or wheel to travel.",
    when: ["Project indexes and case-study reels", "Creative agency homepages"],
    file: "three-d/WaveGallery.tsx",
    tags: ["wave", "3d", "gallery", "infinite", "fog", "ribbon"],
    a11y: "Decorative motion; wheel/drag optional; idle travel stops under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "sphere-gallery",
    title: "Sphere gallery",
    category: "3D",
    summary: "Images spread over a sphere (Fibonacci lattice), billboarded, rotating on both axes with inertia.",
    when: ["Community / team / customer photo walls", "Globe-style showcases"],
    file: "three-d/SphereGallery.tsx",
    tags: ["sphere", "globe", "3d gallery", "images", "drag", "inertia"],
    a11y: "role=\"img\" with label; idle spin stops under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "scroll-tunnel",
    title: "Scroll tunnel",
    category: "3D",
    summary: "Fly forward through a corridor of images as you scroll; cards emerge from the fog and pass the camera.",
    when: ["Immersive storytelling intros", "Portfolio fly-throughs"],
    file: "three-d/ScrollTunnel.tsx",
    tags: ["tunnel", "scroll", "3d", "fly through", "z-axis", "immersive"],
    a11y: "Focusable scroll container; content is decorative imagery. Offer a skip link past long scroll scenes.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "swipe-stack",
    title: "Swipe card stack",
    category: "3D",
    summary: "Tinder-style stack: drag the top card, it tilts and flies off past a threshold; buttons and arrow keys do the same.",
    when: ["Onboarding choices, matching, quick triage", "Mobile-first decision UIs"],
    file: "three-d/SwipeStack.tsx",
    tags: ["swipe", "tinder", "card stack", "drag", "gesture", "mobile"],
    a11y: "Buttons + arrow keys alternative to dragging; decisions announced via aria-live.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "flip-card",
    title: "3D flip card",
    category: "3D",
    summary: "Two faces back-to-back that flip on Y; hover for pointers, click/Enter for everyone.",
    when: ["Feature teasers, team bios, flashcards", "Pricing details on the back"],
    file: "three-d/FlipCard.tsx",
    tags: ["flip", "card", "3d", "backface-visibility", "hover"],
    a11y: "Button with aria-pressed; hidden face aria-hidden so only the visible side is read.",
  },
  {
    slug: "depth-parallax",
    title: "Depth parallax layers",
    category: "3D",
    summary: "Scene layers shift by depth against the pointer plus a slight whole-card tilt; CSS variables, no re-renders.",
    when: ["Hero illustrations, game / app promos", "Product cards with foreground props"],
    file: "three-d/DepthParallax.tsx",
    tags: ["parallax", "layers", "depth", "hover", "tilt", "illustration"],
    a11y: "role=\"img\" with description; transforms disabled under reduced motion.",
  },
  {
    slug: "cube-slider",
    title: "3D cube slider",
    category: "3D",
    summary: "Four slides on the faces of a rotating cube; prev/next turn it 90°.",
    when: ["Product angle views, before/after, step-throughs"],
    file: "three-d/CubeSlider.tsx",
    tags: ["cube", "slider", "3d", "carousel", "rotate"],
    a11y: "Labelled prev/next buttons, current face announced, other faces aria-hidden.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "arc-carousel",
    title: "Arc carousel",
    category: "3D",
    summary: "Cards riding a huge circle; one shared transform-origin means rotate() alone places and tilts them.",
    when: ["Featured work, app screenshots, testimonials"],
    file: "three-d/ArcCarousel.tsx",
    tags: ["arc", "carousel", "rotate", "transform-origin", "slider"],
    a11y: "listbox/option with aria-selected, arrow keys, position announced.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "extruded-text",
    title: "Extruded 3D text",
    category: "3D",
    summary: "Chunky 3D type from a generated stack of text-shadows, tilting toward the pointer.",
    when: ["Playful headlines, posters, game UIs"],
    file: "three-d/ExtrudedText.tsx",
    tags: ["3d text", "text-shadow", "extrude", "typography", "retro"],
    a11y: "Real text, still selectable and readable; tilt off under reduced motion. Keep contrast of face colour vs background.",
  },
  {
    slug: "split-text-reveal",
    title: "Split text reveal",
    category: "Text",
    summary: "Headline split into words or letters that slide up from masks with a stagger when scrolled into view.",
    when: ["Hero headlines, section titles, manifesto lines"],
    file: "text/SplitTextReveal.tsx",
    tags: ["split text", "stagger", "reveal", "headline", "gsap alternative"],
    a11y: "Full sentence via aria-label, split spans aria-hidden; shown immediately under reduced motion.",
  },
  {
    slug: "typewriter",
    title: "Typewriter",
    category: "Text",
    summary: "Types, holds, deletes and cycles phrases with a blinking caret.",
    when: ["Hero taglines listing use cases"],
    file: "text/Typewriter.tsx",
    tags: ["typewriter", "typing", "rotating words", "caret"],
    a11y: "Screen readers get each whole phrase once (polite live region), not every keystroke; no typing under reduced motion.",
  },
  {
    slug: "shimmer-text",
    title: "Shimmer text & running border",
    category: "Text",
    summary: "Gradient shine sweeping across text, and a conic-gradient border that runs around a button. @property animations.",
    when: ["Announcement pills, launch badges, premium CTAs"],
    file: "text/ShimmerText.tsx",
    tags: ["shimmer", "gradient text", "conic gradient", "animated border", "@property"],
    a11y: "Text remains real text; animations stop under reduced motion. Check the muted gradient stops still pass contrast.",
  },
  {
    slug: "magnetic-button",
    title: "Magnetic button",
    category: "Motion",
    summary: "Button leans toward the pointer inside its hover area, label leans further, springs back on leave.",
    when: ["Primary CTAs and nav on creative sites"],
    file: "motion/MagneticButton.tsx",
    tags: ["magnetic", "hover", "cursor", "button", "micro-interaction"],
    a11y: "Pure pointer effect; the button works normally for keyboard. Disabled under reduced motion.",
  },
  {
    slug: "custom-cursor",
    title: "Custom cursor",
    category: "Motion",
    summary: "Dot + eased ring cursor with blend-mode inversion; grows and shows a label over [data-cursor] elements.",
    when: ["Portfolio and agency sites with big media"],
    file: "motion/CustomCursor.tsx",
    tags: ["cursor", "custom cursor", "mix-blend-mode", "hover label", "lerp"],
    a11y: "Only on fine pointers; native cursor kept under reduced motion and on touch. Never hide the cursor over form fields in real use.",
  },
  {
    slug: "image-trail",
    title: "Cursor image trail",
    category: "Motion",
    summary: "Images drop along the pointer path and fade/scale out, recycled from a fixed pool.",
    when: ["Portfolio heroes, photography, fashion"],
    file: "motion/ImageTrail.tsx",
    tags: ["image trail", "cursor", "hover", "web animations api", "playful"],
    a11y: "Decorative, aria-hidden; off under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "stacking-cards",
    title: "Sticky stacking cards",
    category: "Motion",
    summary: "Cards pin with increasing offsets and pile up as you scroll; buried cards shrink via a view timeline. No JS.",
    when: ["Process steps, services, feature stories"],
    file: "motion/StackingCards.tsx",
    tags: ["sticky", "stack", "scroll", "cards", "animation-timeline"],
    a11y: "Plain articles in reading order; shrink effect removed under reduced motion.",
  },
  {
    slug: "zoom-out-hero",
    title: "Zoom-out framed hero",
    category: "Motion",
    summary: "Full-bleed hero image that shrinks into a rounded window as you scroll (clip-path), headline scaling with it.",
    when: ["Studio / product launches, cinematic intros"],
    file: "motion/ZoomOutHero.tsx",
    tags: ["hero", "scroll", "clip-path", "zoom", "frame", "cinematic"],
    a11y: "Image has alt text; end state shown under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "scroll-progress",
    title: "Reading progress bar",
    category: "Motion",
    summary: "Progress bar driven by a CSS scroll timeline, no JS.",
    when: ["Articles, docs, long landing pages"],
    file: "motion/ScrollProgress.tsx",
    tags: ["progress", "scroll", "reading", "animation-timeline", "indicator"],
    a11y: "Decorative (aria-hidden); the scrollbar remains the accessible indicator.",
  },
  {
    slug: "hover-image-list",
    title: "Hover image list",
    category: "Motion",
    summary: "Editorial list; hovering a row floats its image near the cursor while other rows dim.",
    when: ["Work indexes, menus, article lists"],
    file: "motion/HoverImageList.tsx",
    tags: ["hover", "image reveal", "list", "editorial", "portfolio index"],
    a11y: "Rows are links; keyboard focus also reveals the image; image decorative.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "form-controls",
    title: "Form controls",
    category: "Components",
    summary: "Input with hint/error, switch, checkbox, radio cards, select and range, all native elements restyled.",
    when: ["Every form: settings, signup, checkout"],
    file: "components/FormControls.tsx",
    tags: ["form", "input", "switch", "checkbox", "radio", "select", "slider", "validation"],
    a11y: "Native controls; labels, aria-describedby for hints/errors, aria-invalid, role=switch with aria-checked, visible focus.",
  },
  {
    slug: "animated-tabs",
    title: "Animated tabs",
    category: "Components",
    summary: "Segmented tabs with a sliding indicator, full WAI-ARIA tabs keyboard pattern.",
    when: ["Section switching, settings, pricing periods"],
    file: "components/AnimatedTabs.tsx",
    tags: ["tabs", "segmented control", "indicator", "aria tabs"],
    a11y: "tablist/tab/tabpanel, roving tabindex, Arrow/Home/End keys, aria-controls/labelledby.",
  },
  {
    slug: "accordion",
    title: "Accordion / FAQ",
    category: "Components",
    summary: "Native <details> accordion with smooth height (interpolate-size) and exclusive open via name.",
    when: ["FAQs, settings groups, long content"],
    file: "components/Accordion.tsx",
    tags: ["accordion", "faq", "details", "collapsible", "disclosure"],
    a11y: "Native details/summary semantics and keyboard; animation off under reduced motion.",
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    category: "Components",
    summary: "Shows on hover and focus, hides on Escape, linked with aria-describedby.",
    when: ["Icon buttons, truncated labels, shortcuts"],
    file: "components/Tooltip.tsx",
    tags: ["tooltip", "hint", "popover", "aria-describedby"],
    a11y: "role=tooltip + aria-describedby; focus shows it; Escape dismisses. Never put essential info only in a tooltip.",
  },
  {
    slug: "confirm-modal",
    title: "Confirm modal",
    category: "Components",
    summary: "Destructive-action dialog: focus starts on Cancel, type-to-confirm guard, native <dialog>.",
    when: ["Delete / irreversible actions"],
    file: "components/ConfirmModal.tsx",
    tags: ["modal", "dialog", "confirm", "destructive", "delete"],
    a11y: "showModal focus trap + Esc, aria-labelledby/describedby, safe default focus, result announced.",
  },
  {
    slug: "dock",
    title: "Magnifying dock",
    category: "Components",
    summary: "macOS-style dock: icons grow with a cosine falloff by distance to the pointer.",
    when: ["App launchers, playful nav, portfolio toolbars"],
    file: "components/Dock.tsx",
    tags: ["dock", "macos", "magnify", "navigation", "hover"],
    a11y: "Labelled buttons in a nav landmark; focus magnifies and shows the label; no transition under reduced motion.",
  },
  {
    slug: "otp-input",
    title: "OTP / code input",
    category: "Components",
    summary: "Six boxes that act as one field: auto-advance, backspace, arrows, paste-to-fill, SMS autofill.",
    when: ["2FA, email verification, PIN entry"],
    file: "components/OtpInput.tsx",
    tags: ["otp", "one-time code", "pin", "verification", "2fa"],
    a11y: "Labelled group, each box labelled \"Digit n of 6\", inputmode numeric, completion announced.",
  },
  {
    slug: "stepper",
    title: "Stepper",
    category: "Components",
    summary: "Numbered steps with a filling rail and checks for completed steps.",
    when: ["Onboarding, checkout, multi-step forms"],
    file: "components/Stepper.tsx",
    tags: ["stepper", "wizard", "progress", "steps", "onboarding"],
    a11y: "<ol> with aria-current=\"step\" and visually hidden state text.",
  },
  {
    slug: "loading-states",
    title: "Loading, empty & error states",
    category: "Components",
    summary: "Skeleton shimmer, empty state, error with retry and loaded list: the four states of any data view.",
    when: ["Every list, table, dashboard widget"],
    file: "components/LoadingStates.tsx",
    tags: ["skeleton", "empty state", "error state", "loading", "placeholder"],
    a11y: "aria-busy while loading, role=alert on error, shimmer stops under reduced motion.",
  },
  {
    slug: "starfield",
    title: "Warp starfield",
    category: "Backgrounds",
    summary: "Stars rushing toward the camera as streaks; hover engages warp speed. Canvas 2D.",
    when: ["Space / AI / launch heroes, 404 pages"],
    file: "backgrounds/Starfield.tsx",
    tags: ["starfield", "space", "warp", "canvas", "particles", "background"],
    a11y: "Decorative; slow drift only under reduced motion; pauses off-screen.",
  },
  {
    slug: "perspective-grid",
    title: "Synthwave perspective grid",
    category: "Backgrounds",
    summary: "Neon grid floor scrolling toward you under a striped sun. Pure CSS.",
    when: ["Retro, gaming, music and event sites"],
    file: "backgrounds/PerspectiveGrid.tsx",
    tags: ["synthwave", "retro", "grid", "perspective", "neon", "80s"],
    a11y: "role=img with description; static under reduced motion.",
  },
  {
    slug: "morph-blob",
    title: "Morphing blob",
    category: "Backgrounds",
    summary: "Organic gradient blob cycling border-radius shapes while rotating. No JS.",
    when: ["Behind avatars, product shots, hero words"],
    file: "backgrounds/MorphBlob.tsx",
    tags: ["blob", "organic", "gradient", "border-radius", "background"],
    a11y: "Decorative, aria-hidden; static under reduced motion.",
  },
  {
    slug: "testimonial-wall",
    title: "Testimonial wall",
    category: "Sections",
    summary: "Masonry of quote cards in columns scrolling opposite ways with faded edges.",
    when: ["Social proof on landing pages"],
    file: "sections/TestimonialWall.tsx",
    tags: ["testimonials", "social proof", "masonry", "marquee", "reviews"],
    a11y: "figure/blockquote/figcaption; duplicate copies aria-hidden; pauses on hover; static under reduced motion.",
  },
  {
    slug: "split-hero",
    title: "Split hero",
    category: "Sections",
    summary: "Headline, announcement pill, dual CTA and avatar proof beside a rotated image collage.",
    when: ["SaaS and product landing pages"],
    file: "sections/SplitHero.tsx",
    tags: ["hero", "landing page", "cta", "collage", "social proof"],
    a11y: "Single h1; collage aria-hidden; CTAs are buttons/links with clear text.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "logo-cloud",
    title: "Logo cloud & stats",
    category: "Sections",
    summary: "Greyscale logos that light up on hover plus a stats band as a definition list.",
    when: ["Credibility band under a hero"],
    file: "sections/LogoCloud.tsx",
    tags: ["logos", "clients", "stats", "social proof", "trust"],
    a11y: "Stats as <dl> pairs; replace text logos with SVGs that have alt text.",
  },
  {
    slug: "auth-screen",
    title: "Auth screen",
    category: "Screens",
    summary: "Split sign-in/up: brand quote panel, social buttons, email/password with show/hide and correct autocomplete.",
    when: ["Login, signup, invite acceptance"],
    file: "screens/AuthScreen.tsx",
    tags: ["login", "signup", "auth", "form", "password"],
    a11y: "Labelled inputs, autocomplete tokens for password managers, show/hide with aria-pressed, errors in aria-live.",
  },
  {
    slug: "kanban-board",
    title: "Kanban board",
    category: "Screens",
    summary: "Columns with drag-and-drop cards plus a per-card \"Move to\" select as the keyboard path.",
    when: ["Task boards, pipelines, CRMs"],
    file: "screens/KanbanBoard.tsx",
    tags: ["kanban", "drag and drop", "board", "tasks", "trello"],
    a11y: "DnD has a select-based alternative; columns are labelled sections; moves announced.",
  },
  {
    slug: "chat-ui",
    title: "AI chat screen",
    category: "Screens",
    summary: "Message log, bubbles, typing indicator, suggestion chips and an auto-growing composer.",
    when: ["AI assistants, support chat, messaging"],
    file: "screens/ChatUI.tsx",
    tags: ["chat", "ai assistant", "messages", "composer", "chatbot"],
    a11y: "role=log live region, speaker prefixes for screen readers, Enter/Shift+Enter, labelled composer and send button.",
  },
  {
    slug: "charts",
    title: "SVG charts (line, heatmap, radar)",
    category: "Data viz",
    summary: "Area chart with crosshair + keyboard, contribution heatmap and radar chart, all hand-drawn SVG.",
    when: ["Dashboards without a chart library", "Profiles, analytics, comparisons"],
    file: "dataviz/Charts.tsx",
    tags: ["chart", "line chart", "area chart", "heatmap", "radar", "svg"],
    a11y: "role=img with summaries; line chart is keyboard navigable with values in aria-live.",
  },
  {
    slug: "glitch-text",
    title: "Glitch text",
    category: "Text",
    summary: "RGB-split glitch from two clip-path-banded pseudo-element copies; plays on hover.",
    when: ["Tech, gaming, music and 404 pages", "Hover accent on a single word, not paragraphs"],
    file: "text/GlitchText.tsx",
    tags: ["glitch", "rgb split", "clip-path", "hover", "cyberpunk"],
    a11y: "Real text; copies are pseudo-elements (not read twice). Hover-only by default; disabled under reduced motion (flicker can trigger discomfort).",
  },
  {
    slug: "link-hover-effects",
    title: "Link hover effects (8)",
    category: "Text",
    summary: "Grow underline, centre-out, strike, highlighter, text roll, arrow nudge, double line, colour sweep: pure CSS classes.",
    when: ["Nav links, inline links, footers", "Pick one per site and use it everywhere"],
    file: "text/LinkHoverEffects.tsx",
    tags: ["link", "underline", "hover", "css only", "navigation"],
    a11y: "Focus-visible triggers the same effect and keeps an outline; transitions off under reduced motion.",
  },
  {
    slug: "floating-inputs",
    title: "Input effects",
    category: "Components",
    summary: "Floating label, underline-draw and border-trace inputs using :placeholder-shown, no JS.",
    when: ["Signup, contact and checkout forms", "Minimal forms where labels double as placeholders"],
    file: "components/FloatingInputs.tsx",
    tags: ["input", "floating label", "form", "focus effect", "css only"],
    a11y: "Real <label for>; label never disappears (it moves); focus is visible; transitions off under reduced motion.",
  },
  {
    slug: "caption-hover",
    title: "Image caption hovers (6)",
    category: "Motion",
    summary: "Slide-up caption, zoom + dim, split reveal, frame draw, circle clip reveal and greyscale-to-colour.",
    when: ["Portfolio grids, product cards, blog tiles"],
    file: "motion/CaptionHover.tsx",
    tags: ["hover", "image", "caption", "card", "portfolio", "clip-path"],
    a11y: "Cards are links; :focus-visible gets the hover state so keyboard users see captions.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "direction-aware-hover",
    title: "Direction-aware hover",
    category: "Motion",
    summary: "The overlay slides in from the edge the pointer entered and leaves through the edge it exits.",
    when: ["Image grids, team photos, galleries"],
    file: "motion/DirectionAwareHover.tsx",
    tags: ["hover", "direction", "overlay", "grid", "pointer"],
    a11y: "Links; focus shows the overlay from below; no transition under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "image-tilt",
    title: "Layered image tilt",
    category: "Motion",
    summary: "Image plus translucent copies and a title move at different depths with the pointer.",
    when: ["Hero images, featured posts, album art"],
    file: "motion/ImageTilt.tsx",
    tags: ["tilt", "parallax", "layers", "hover", "depth"],
    a11y: "Only the base image has alt text; copies aria-hidden; pointer effect disabled under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "particle-button",
    title: "Particle burst button",
    category: "Components",
    summary: "Click spawns dots that fly out and fade via WAAPI; exported burst() works on any element.",
    when: ["Like / celebrate / success moments"],
    file: "components/ParticleButton.tsx",
    tags: ["particles", "confetti", "burst", "click", "celebrate"],
    a11y: "Native button; particles decorative; skipped under reduced motion.",
  },
  {
    slug: "distort-button",
    title: "SVG distortion button",
    category: "Components",
    summary: "feTurbulence + feDisplacementMap wobble on hover/focus, animated then removed so text stays crisp.",
    when: ["Experimental / art / music sites"],
    file: "components/DistortButton.tsx",
    tags: ["svg filter", "distortion", "turbulence", "hover", "glitch"],
    a11y: "Filter only during the brief animation; off under reduced motion.",
  },
  {
    slug: "progress-button",
    title: "Progress button",
    category: "Components",
    summary: "The button fills as its own progress bar, then morphs into a success check.",
    when: ["Uploads, submits, long actions"],
    file: "components/ProgressButton.tsx",
    tags: ["progress", "button", "upload", "loading", "morph"],
    a11y: "aria-busy, a role=progressbar with values while busy, completion announced, disabled during work.",
  },
  {
    slug: "click-ripple",
    title: "Click ripple & shockwave",
    category: "Motion",
    summary: "Ripple from the exact press point (or centre for keyboard), plus a ring shockwave variant.",
    when: ["Buttons, cards, list rows needing tactile feedback"],
    file: "motion/ClickRipple.tsx",
    tags: ["ripple", "material", "click", "feedback", "waapi"],
    a11y: "Decorative; skipped under reduced motion; works for keyboard activation.",
  },
  {
    slug: "gooey-menu",
    title: "Gooey FAB menu",
    category: "Components",
    summary: "Action bubbles melt out of a floating button via an SVG goo filter; icons stay crisp on a separate layer.",
    when: ["Mobile quick actions, creative tools"],
    file: "components/GooeyMenu.tsx",
    tags: ["gooey", "fab", "svg filter", "menu", "blob"],
    a11y: "Toggle has aria-expanded; action buttons labelled and removed from tab order when closed.",
  },
  {
    slug: "animated-icons",
    title: "Animated toggle icons",
    category: "Components",
    summary: "Hamburger↔close, heart with burst ring, bookmark fill, play↔pause path morph, self-drawing check.",
    when: ["Nav toggles, like/save buttons, media controls"],
    file: "components/AnimatedIcons.tsx",
    tags: ["icons", "toggle", "hamburger", "like", "svg", "morph"],
    a11y: "Buttons with aria-label and aria-pressed; animations off under reduced motion.",
  },
  {
    slug: "pixel-transition",
    title: "Pixel page transition",
    category: "Motion",
    summary: "A grid of squares covers the screen in random order, the page swaps, then it clears.",
    when: ["Page/route changes on portfolio and creative sites"],
    file: "motion/PixelTransition.tsx",
    tags: ["page transition", "pixel", "grid", "route change"],
    a11y: "Nav uses aria-current; instant swap under reduced motion.",
  },
  {
    slug: "layered-wipe",
    title: "Layered wipe transition",
    category: "Motion",
    summary: "Three coloured panels sweep across with a stagger, page swaps under cover, they exit the other side.",
    when: ["Studio / agency route transitions"],
    file: "motion/LayeredWipe.tsx",
    tags: ["page transition", "wipe", "clip-path", "curtain", "stagger"],
    a11y: "Panels aria-hidden; instant swap under reduced motion; aria-current on nav.",
  },
  {
    slug: "scroll-blur-text",
    title: "Scroll typography (blur, highlight, fill)",
    category: "Text",
    summary: "Words un-blur, markers sweep behind key phrases, and words fill with colour as you read. CSS view timelines only.",
    when: ["Manifestos, about pages, long-form storytelling"],
    file: "text/ScrollBlurText.tsx",
    tags: ["scroll", "typography", "blur", "highlight", "animation-timeline", "css only"],
    a11y: "Text readable without support; animations off under reduced motion.",
  },
  {
    slug: "scroll-3d-grid",
    title: "3D grid on scroll",
    category: "3D",
    summary: "Images rotate in from depth as they enter and tilt away as they leave, via CSS view timelines.",
    when: ["Galleries, lookbooks, case-study indexes"],
    file: "three-d/Scroll3DGrid.tsx",
    tags: ["3d", "scroll", "grid", "perspective", "animation-timeline"],
    a11y: "Flat grid without support or under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "elastic-columns",
    title: "Elastic grid scroll",
    category: "Motion",
    summary: "Each column follows scroll with its own lag; the middle one counter-moves, so the grid stretches and settles.",
    when: ["Image-heavy portfolios and lookbooks"],
    file: "motion/ElasticColumns.tsx",
    tags: ["scroll", "parallax", "grid", "lerp", "elastic"],
    a11y: "Plain grid under reduced motion; rAF stops when settled.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "pixel-image-load",
    title: "Pixelated image reveal",
    category: "Motion",
    summary: "Images resolve from big crisp blocks to full resolution when scrolled into view (canvas, smoothing off).",
    when: ["Photography, retro/gaming, editorial reveals"],
    file: "motion/PixelImageLoad.tsx",
    tags: ["pixel", "image reveal", "canvas", "loading", "scroll"],
    a11y: "Real <img> with alt underneath; canvas aria-hidden; skipped under reduced motion. Needs CORS-enabled images.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "flashlight-reveal",
    title: "Flashlight reveal",
    category: "Motion",
    summary: "A dark, blurred cover with a radial mask hole that follows the pointer, plus a Reveal-all button.",
    when: ["Mystery/teaser launches, games, night themes"],
    file: "motion/FlashlightReveal.tsx",
    tags: ["mask", "spotlight", "cursor", "reveal", "mask-image"],
    a11y: "Image has alt text; button reveals everything for keyboard/touch; aria-pressed.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "liquid-slideshow",
    title: "WebGL liquid slideshow",
    category: "Backgrounds",
    summary: "Noise-displaced UVs melt one image into the next in a single fragment shader, no library.",
    when: ["Hero slideshows, fashion/product campaigns"],
    file: "backgrounds/LiquidSlideshow.tsx",
    tags: ["webgl", "slideshow", "distortion", "displacement", "shader", "transition"],
    a11y: "Carousel region with labelled buttons and live position; plain crossfade without WebGL or under reduced motion.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "fullscreen-menu",
    title: "Fullscreen overlay menu",
    category: "Components",
    summary: "Circle clip-path reveal from the toggle, big links sliding up from masks, hover image previews.",
    when: ["Portfolio / agency / brand site navigation"],
    file: "components/FullscreenMenu.tsx",
    tags: ["menu", "overlay", "navigation", "clip-path", "stagger"],
    a11y: "aria-expanded/controls, focus moves in and returns to toggle, Esc closes, background inert, closed links untabbable.",
    deps: ["three-d/_shared.ts (img() placeholder URLs, makeSpinner drag helper)"],
  },
  {
    slug: "preloader",
    title: "Counter preloader",
    category: "Motion",
    summary: "Big 000→100 counter with realistic pauses and a thin bar, then curtains split to reveal the page.",
    when: ["Heavy WebGL/media sites that really need a load step"],
    file: "motion/Preloader.tsx",
    tags: ["preloader", "loader", "counter", "intro", "curtain"],
    a11y: "role=progressbar with values; skipped under reduced motion. Don't fake loading on fast pages.",
  },
  {
    slug: "morph-shapes",
    title: "Scroll morphing shapes",
    category: "Backgrounds",
    summary: "One SVG path lerps between blob keyframes while rotating and shifting hue as you scroll.",
    when: ["Decorative section backgrounds, storytelling pages"],
    file: "backgrounds/MorphShapes.tsx",
    tags: ["svg", "morph", "path", "scroll", "blob"],
    a11y: "Decorative, aria-hidden; static under reduced motion.",
  },
  {
    slug: "cursor-teddy",
    title: "Cursor-following 3D teddy",
    category: "3D Motion",
    summary: "A real-3D teddy (primitives, no model file) whose head turns to follow the cursor anywhere on the page, with blinking and idle breathing.",
    when: ["Playful hero mascots, 404 pages, kids / toy / pet brands", "Swap the head group for a GLTF bone to drive a real character"],
    file: "motion3d/CursorTeddy.tsx",
    tags: ["three.js", "react three fiber", "cursor follow", "look at", "mascot", "character", "3d"],
    a11y: "Canvas wrapped in role=img with a description; idle breathing stops under reduced motion; purely decorative (no information in the motion).",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "cursor-robot",
    title: "Cursor-following 3D robot",
    category: "3D Motion",
    summary: "Boxy robot mascot: head turns to the cursor, glowing eyes slide inside the visor, antenna springs with lag, eyes brighten on hover.",
    when: ["AI / SaaS / dev-tool mascots", "Hero characters that react to the visitor"],
    file: "motion3d/CursorRobot.tsx",
    tags: ["three.js", "react three fiber", "cursor follow", "robot", "mascot", "character", "eyes"],
    a11y: "Canvas wrapped in role=img with a description; idle motion stops under reduced motion; decorative (no information in the motion).",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "floating-shapes",
    title: "Floating shapes that dodge the cursor",
    category: "3D Motion",
    summary: "Glossy clearcoat 3D shapes bob in space and get pushed away by the cursor (pointer projected onto the scene), springing back home.",
    when: ["Playful hero backgrounds", "Product / agency landing pages"],
    file: "motion3d/FloatingShapes.tsx",
    tags: ["three.js", "floating", "repel", "cursor", "physics", "shapes", "hero"],
    a11y: "Canvas wrapped in role=img with a description; idle motion stops under reduced motion; decorative (no information in the motion).",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "scroll-model",
    title: "Scroll-driven 3D object",
    category: "3D Motion",
    summary: "A 3D planet turns, slides, tilts and recolours through keyframes as text sections scroll past, like an Apple-style product story.",
    when: ["Product pages that reveal features by scrolling", "Storytelling / scrollytelling"],
    file: "motion3d/ScrollModel.tsx",
    tags: ["three.js", "scroll", "scrollytelling", "product", "keyframes", "3d"],
    a11y: "Canvas is decorative; the text sections carry the content and stay readable; container is focusable for keyboard scrolling.",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "glass-shape",
    title: "Refractive glass torus",
    category: "3D Motion",
    summary: "A glass torus (MeshTransmissionMaterial) with chromatic aberration refracts big type behind it and tilts toward the cursor.",
    when: ["Premium hero sections", "Brand moments where the headline should feel tangible"],
    file: "motion3d/GlassShape.tsx",
    tags: ["three.js", "glass", "refraction", "transmission", "chromatic aberration", "hero"],
    a11y: "Canvas wrapped in role=img with a description; idle motion stops under reduced motion; decorative (no information in the motion).",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "distort-blob",
    title: "Liquid 3D blob",
    category: "3D Motion",
    summary: "Noise-distorted sphere that leans toward the cursor, wobbles harder and swells on hover, and changes colour on click.",
    when: ["AI / voice / music product heroes", "Interactive brand orbs"],
    file: "motion3d/DistortBlob.tsx",
    tags: ["three.js", "blob", "distort", "liquid", "orb", "hover", "ai"],
    a11y: "Canvas wrapped in role=img with a description; idle motion stops under reduced motion; decorative (no information in the motion).",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "particle-morph",
    title: "Particle morph",
    category: "3D Motion",
    summary: "4,000 particles ripple between a sphere, cube, torus knot and wave plane, rotating toward the cursor.",
    when: ["Data / AI / tech heroes", "Section transitions and loading moments"],
    file: "motion3d/ParticleMorph.tsx",
    tags: ["three.js", "particles", "morph", "points", "shape", "additive"],
    a11y: "Shape picker is a radiogroup; canvas labelled with the current shape; instant morph and no drift under reduced motion.",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "keycap-3d",
    title: "3D keycap",
    category: "3D Motion",
    summary: "A glossy keycap that tilts toward the cursor and physically presses on click, Space/Enter, or when you type its letter.",
    when: ["Keyboard / dev-tool / shortcut marketing", "Playful CTAs"],
    file: "motion3d/Keycap3D.tsx",
    tags: ["three.js", "keyboard", "keycap", "press", "button", "3d"],
    a11y: "The canvas sits inside a real button (aria-pressed); works with Space/Enter and the key itself.",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
  {
    slug: "product-viewer",
    title: "360\u00b0 product viewer",
    category: "3D Motion",
    summary: "Drag-to-orbit product with idle auto-rotate, colourway swatches and hotspots pinned to the model.",
    when: ["E-commerce product pages", "Hardware / packaging showcases"],
    file: "motion3d/ProductViewer.tsx",
    tags: ["three.js", "product", "orbit controls", "360", "configurator", "ecommerce", "hotspots"],
    a11y: "Canvas labelled with the current colourway; swatches are a radiogroup; auto-rotate off under reduced motion; hotspot text is real HTML.",
    deps: ["three", "@react-three/fiber", "@react-three/drei", "motion3d/_pointer.ts (window pointer hook)"],
  },
]

/** Sorted by category so the grid and prev/next follow the sidebar order. */
export const META: PatternMeta[] = ALL.map((p, i) => ({ p, i }))
  .sort((a, b) => CATEGORIES.indexOf(a.p.category) - CATEGORIES.indexOf(b.p.category) || a.i - b.i)
  .map(({ p }) => p)
