/*
 * Pattern metadata: plain data, no React imports, so the build (vite.config.ts)
 * can read it to generate llms.txt, patterns.json and per-pattern docs.
 * Add a pattern = add an entry here + the file under src/patterns/.
 */
export const CATEGORIES = [
  'Foundations',
  'Components',
  'Text',
  'Motion',
  'Backgrounds',
  '3D',
  'Layouts',
  'Sections',
  'Screens',
  'Data viz',
  'Recipes',
] as const

export type Category = (typeof CATEGORIES)[number]

export type PatternMeta = {
  slug: string
  title: string
  category: Category
  summary: string
  /** When to reach for this. Every entry needs at least one. */
  when: string[]
  /** Source file under src/patterns, shown in the code panel. */
  file: string
  source?: { label: string; url: string }
  /** Search keywords for humans and AI: technique names, use cases, look. */
  tags?: string[]
  /** Accessibility notes: keyboard, screen reader, reduced-motion behaviour. */
  a11y?: string
  /** Runtime deps beyond React + Tailwind. Empty = copy the file and go. */
  deps?: string[]
}

const ALL: PatternMeta[] = [
  {
    slug: 'tokens',
    tags: ["design tokens", "css variables", "theme", "dark mode", "color", "typography", "spacing"],
    a11y: "Colour pairs meet WCAG AA for body text in both themes. Motion durations collapse to 0 under prefers-reduced-motion.",
    title: 'Design tokens',
    category: 'Foundations',
    summary: 'Color, type, spacing, radius, elevation and motion tokens. Light/dark aware, no flash.',
    when: [
      'Starting any new project: copy src/tokens/tokens.css first',
      'Plain HTML projects too; the file has no framework dependency',
    ],
    file: 'foundations/Tokens.tsx',
  },
  {
    slug: 'buttons',
    tags: ["button", "cta", "loading", "variants"],
    a11y: "Native <button>; aria-busy while loading; disabled state removes pointer events; visible focus ring from tokens.",
    title: 'Buttons',
    category: 'Components',
    summary: 'Primary / secondary / ghost / danger, three sizes, loading state and a tactile press.',
    when: ['Any clickable action', 'Swap --accent to rebrand without touching the component'],
    file: 'components/Buttons.tsx',
  },
  {
    slug: 'scroll-reveal',
    tags: ["scroll animation", "reveal", "fade in", "animation-timeline", "css only"],
    a11y: "Content is visible without support (@supports guard). Animation removed under reduced motion.",
    title: 'Scroll reveal (CSS only)',
    category: 'Motion',
    summary: 'Elements fade and rise as they enter the viewport using animation-timeline: view(). Zero JS.',
    when: [
      'Landing pages and long-form sections',
      'Prefer this over IntersectionObserver when you only need enter animations',
    ],
    file: 'motion/ScrollReveal.tsx',
    source: {
      label: 'MDN: scroll-driven animations',
      url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll-driven_animations',
    },
  },
  {
    slug: 'view-transition-grid',
    tags: ["view transitions", "shared element", "page transition", "morph", "gallery"],
    a11y: "Plain buttons; without View Transitions support the swap is instant. Disable transitions for reduced motion globally.",
    title: 'Shared-element view transition',
    category: 'Motion',
    summary: 'A card morphs into its detail view with the View Transitions API. Falls back to an instant swap.',
    when: ['Grid → detail navigation', 'Gallery / product / project pages (MemoryShards-style)'],
    file: 'motion/ViewTransitionGrid.tsx',
    source: {
      label: 'MDN: View Transition API',
      url: 'https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API',
    },
  },
  {
    slug: 'count-up',
    tags: ["counter", "stats", "numbers", "kpi", "intersection observer"],
    a11y: "Final value shown immediately under reduced motion; tabular-nums avoids layout shift.",
    title: 'Count-up stats',
    category: 'Motion',
    summary: 'Numbers animate from 0 when scrolled into view, with tabular figures so width stays stable.',
    when: ['Stat tiles on landing pages and dashboards'],
    file: 'motion/CountUp.tsx',
    source: { label: 'For fancier digit rolls: number-flow', url: 'https://github.com/barvian/number-flow' },
  },
  {
    slug: 'command-palette',
    tags: ["cmdk", "search", "command menu", "keyboard", "dialog", "ctrl k"],
    a11y: "Native <dialog> traps focus and handles Esc; listbox/option roles with aria-selected; full keyboard nav.",
    title: 'Command palette',
    category: 'Components',
    summary: 'Ctrl/⌘K launcher on the native <dialog>: focus trap, Esc and backdrop for free, arrow-key navigation.',
    when: ['Any app with more than a handful of pages or actions', 'Power-user shortcut on top of normal nav, never instead of it'],
    file: 'components/CommandPalette.tsx',
    source: { label: 'Heavier alternative: cmdk', url: 'https://github.com/pacocoursey/cmdk' },
  },
  {
    slug: 'mesh-gradient',
    tags: ["gradient", "background", "blob", "hero", "grain", "css only"],
    a11y: "aria-hidden decorative layer; animation stops under reduced motion.",
    title: 'Animated mesh gradient',
    category: 'Backgrounds',
    summary: 'Three blurred blobs drifting on offset loops, plus SVG grain. Pure CSS hero background.',
    when: ['Hero and section backgrounds', 'Set --mesh-a/b/c to rebrand; pair with big display type'],
    file: 'recipes/MeshGradient.tsx',
    source: { label: 'Generator alternative: Mesh Gradient', url: 'https://www.meshgradient.com/' },
  },
  {
    slug: 'toast',
    tags: ["notification", "snackbar", "feedback", "alert"],
    a11y: "aria-live=\"polite\" region; dismiss buttons labelled.",
    title: 'Toasts',
    category: 'Components',
    summary: 'Provider + useToast() hook. Stacks up to four, auto-dismisses, springs in, announced via aria-live.',
    when: ['Confirming a background action (saved, sent, copied)', 'Never for errors the user must act on; use inline errors'],
    file: 'components/Toast.tsx',
    source: { label: 'Fuller alternative: Sonner', url: 'https://sonner.emilkowal.ski/' },
  },
  {
    slug: 'drawer',
    tags: ["sheet", "side panel", "dialog", "filters", "off-canvas"],
    a11y: "Native <dialog> modal: focus trap, Esc closes, background inert; close button labelled.",
    title: 'Drawer',
    category: 'Components',
    summary: 'Left or right sheet on the native <dialog>, with animated exit and backdrop fade.',
    when: ['Filters, settings, detail panes that keep list context', 'Mobile navigation'],
    file: 'components/Drawer.tsx',
  },
  {
    slug: 'spotlight-card',
    tags: ["hover effect", "glow", "tilt", "cursor", "card"],
    a11y: "Purely decorative on pointer; tilt disabled under reduced motion; content readable without effect.",
    title: 'Spotlight card',
    category: 'Motion',
    summary: 'Cursor-following glow and slight 3D tilt, driven by CSS variables so React never re-renders.',
    when: ['Feature grids and pricing cards on landing pages', 'Sparingly: one group per page'],
    file: 'motion/SpotlightCard.tsx',
  },
  {
    slug: 'bento-grid',
    tags: ["bento", "grid", "features", "layout", "dashboard summary"],
    a11y: "Source order = reading order; collapses to a single column.",
    title: 'Bento grid',
    category: 'Layouts',
    summary: 'Six-column grid with mixed tile spans and dense packing. Collapses to one column on phones.',
    when: ['Feature overviews and dashboard summaries', 'Landing sections that need hierarchy without a long list'],
    file: 'layouts/BentoGrid.tsx',
  },
  {
    slug: 'timeline',
    tags: ["timeline", "activity feed", "history", "events"],
    a11y: "Semantic <ol> + <time>; confidence also conveyed by legend, not colour alone.",
    title: 'Event timeline',
    category: 'Data viz',
    summary: 'Vertical rail with aligned mono timestamps and confidence-coloured dots. Rows reveal on scroll.',
    when: ['Activity feeds, audit logs, reconstructed days (MemoryShards)', 'Order and delivery tracking'],
    file: 'dataviz/Timeline.tsx',
  },
  {
    slug: 'marquee',
    tags: ["marquee", "ticker", "logo wall", "infinite scroll", "loop"],
    a11y: "Duplicate copy is aria-hidden; pauses on hover; static under reduced motion.",
    title: 'Infinite marquee',
    category: 'Recipes',
    summary: 'Seamless looping strip with faded edges, pause on hover, any speed and direction.',
    when: ['Logo walls, tech stacks, testimonials', 'Keep it decorative; nothing essential should scroll away'],
    file: 'recipes/Marquee.tsx',
  },
  {
    slug: "shader-background",
    title: "Shader backgrounds",
    category: "Backgrounds",
    summary: "One WebGL shader, seven looks (mesh, aurora, swirl, voronoi, flame, halftone, metal) and 16 palette presets with a print-like dither.",
    when: ["Hero and section backgrounds that need to feel alive", "Replace background videos: a few KB of GLSL instead of MBs of MP4", "Pick a preset, or pass your own 4-colour palette"],
    file: "backgrounds/ShaderBackground.tsx",
    tags: ["shader", "webgl", "glsl", "aurora", "flame", "voronoi", "halftone", "metal", "gradient", "background", "hero"],
    a11y: "Canvas is aria-hidden. Pauses off-screen and in hidden tabs; renders one still frame under reduced motion; CSS gradient fallback without WebGL.",
  },
  {
    slug: "dot-grid-warp",
    title: "Dot grid warp",
    category: "Backgrounds",
    summary: "A faint dot grid that bends toward the pointer like a rubber sheet under a weight. Canvas 2D, Gaussian falloff.",
    when: ["Interactive hero or section backgrounds", "Developer-tool and AI product pages"],
    file: "backgrounds/DotGridWarp.tsx",
    tags: ["canvas", "interactive background", "dots", "grid", "pointer", "gravity"],
    a11y: "Decorative, aria-hidden. Static grid under reduced motion; idles when the pointer leaves.",
  },
  {
    slug: "scramble-text",
    title: "Scramble text",
    category: "Text",
    summary: "Text decodes into place, characters cycling through glyphs and locking in left to right.",
    when: ["Intro taglines, nav labels, loading states", "Tech, studio and portfolio sites (Alche-style)"],
    file: "text/ScrambleText.tsx",
    tags: ["text effect", "decode", "glitch", "typewriter", "hacker", "intro"],
    a11y: "Final text exposed via aria-label; scrambling glyphs are aria-hidden; instant under reduced motion.",
  },
  {
    slug: "focus-reveal",
    title: "Focus reveal",
    category: "Text",
    summary: "Blurred words come sharp one at a time as a camera-style focus frame travels to each measured word box.",
    when: ["Hero headlines and manifesto lines", "Anywhere one phrase should be read word by word"],
    file: "text/FocusReveal.tsx",
    tags: ["text effect", "blur", "focus", "headline", "camera"],
    a11y: "Sentence exposed via aria-label; frame decorative; all words sharp and static under reduced motion.",
  },
  {
    slug: "blueprint-intro",
    title: "Blueprint intro",
    category: "Motion",
    summary: "Construction lines draw across the frame, then the logo traces itself, then the tagline fades in. SVG stroke animation.",
    when: ["Studio / architecture / engineering landing intros", "Loading screen that shows the brand being built"],
    file: "motion/BlueprintIntro.tsx",
    tags: ["intro", "loader", "svg", "line drawing", "stroke-dashoffset", "logo animation"],
    a11y: "role=\"img\" with a label; finished drawing shown immediately under reduced motion. Keep intros under ~3s and skippable.",
  },
  {
    slug: "pinned-horizontal",
    title: "Pinned horizontal scroll",
    category: "Motion",
    summary: "Vertical scroll drives a horizontal track inside a pinned (sticky) frame. No library.",
    when: ["Process steps, case-study galleries, timelines", "Storytelling sections on landing pages"],
    file: "motion/PinnedHorizontal.tsx",
    tags: ["scroll", "sticky", "pin", "horizontal scroll", "scrollytelling", "parallax"],
    a11y: "Falls back to a normal horizontally scrollable row under reduced motion; container is focusable for keyboard scrolling.",
  },
  {
    slug: "sound-opt-in",
    title: "Sound opt-in",
    category: "Components",
    summary: "Asks before playing sound with two equal choices, remembers the answer and leaves a small equaliser toggle.",
    when: ["Immersive sites with music or UI sounds", "Any autoplay-audio temptation"],
    file: "components/SoundOptIn.tsx",
    tags: ["audio", "consent", "sound toggle", "immersive"],
    a11y: "No audio without an explicit click; toggle uses aria-pressed; animation stops under reduced motion.",
  },
  {
    slug: "liquid-glass-button",
    title: "Liquid glass button",
    category: "Components",
    summary: "Glass pill: backdrop blur + saturate, bevel shadows, and a pointer-following highlight on registered CSS properties.",
    when: ["CTAs over imagery, video or shader backgrounds", "Apple-style glass UI"],
    file: "components/LiquidGlassButton.tsx",
    tags: ["glassmorphism", "liquid glass", "button", "backdrop-filter", "@property"],
    a11y: "Native button. Check text contrast against the actual background; transition removed under reduced motion.",
  },
  {
    slug: "expanding-cards",
    title: "Expanding cards",
    category: "Components",
    summary: "A rail of tall slivers; the active one widens into a full card. Caption laid out at final width so it never rewraps.",
    when: ["Destination / product / portfolio pickers", "Feature showcases with imagery"],
    file: "components/ExpandingCards.tsx",
    tags: ["accordion", "cards", "gallery", "hover expand", "flex-grow"],
    a11y: "Buttons with aria-expanded; activates on hover, focus and click so keyboard and touch work.",
  },
  {
    slug: "morph-pill-card",
    title: "Morph pill card",
    category: "Components",
    summary: "An avatar pill that grows into a full profile card: one surface animating between two sizes.",
    when: ["Team / author / creator previews", "Compact UI that reveals detail on intent"],
    file: "components/MorphPillCard.tsx",
    tags: ["morph", "hover card", "profile", "avatar", "expand"],
    a11y: "Focusable with aria-expanded; opens on focus and toggles with Enter/Space; hidden button removed from tab order when closed.",
  },
  {
    slug: "fan-deck",
    title: "Fan deck",
    category: "Components",
    summary: "A hand of cards splayed from one pivot below the deck; the focused card lifts out of the spread.",
    when: ["Services, steps, pricing plans, collectibles", "Playful portfolio sections"],
    file: "components/FanDeck.tsx",
    tags: ["cards", "fan", "deck", "rotate", "transform-origin"],
    a11y: "Each card is a button with aria-pressed; arrow keys move between cards.",
  },
  {
    slug: "ring-carousel",
    title: "3D ring carousel",
    category: "3D",
    summary: "Cards on a true CSS 3D cylinder; drag to spin with momentum, snaps to the nearest card.",
    when: ["Portfolio and product showcases", "Anywhere a gallery should feel physical"],
    file: "three-d/RingCarousel.tsx",
    tags: ["carousel", "3d", "css 3d", "drag", "momentum", "cylinder", "slider"],
    a11y: "Focusable region with aria-roledescription=\"carousel\", arrow keys rotate, label announces position; no coasting under reduced motion.",
  },
  {
    slug: "coverflow",
    title: "Depth coverflow",
    category: "3D",
    summary: "Coverflow where cards turn edge-on, sink and blur with distance from the active one. Plain CSS 3D.",
    when: ["Album / product / case-study browsers", "Hero galleries"],
    file: "three-d/Coverflow.tsx",
    tags: ["coverflow", "carousel", "3d", "depth", "slider"],
    a11y: "Prev/next buttons labelled, arrow keys, aria-live announces the active item.",
  },
  {
    slug: "particle-globe",
    title: "Particle globe",
    category: "3D",
    summary: "A sphere of points on a Fibonacci lattice with a noise land mask; drag to spin with momentum. Canvas 2D.",
    when: ["Global / network / logistics product heroes", "About pages showing reach"],
    file: "three-d/ParticleGlobe.tsx",
    tags: ["globe", "sphere", "particles", "canvas", "3d", "drag", "earth"],
    a11y: "role=\"img\" with label; pauses off-screen; no idle spin under reduced motion.",
  },
  {
    slug: "pricing-tiers",
    title: "Pricing tiers",
    category: "Sections",
    summary: "Three plans with a monthly/yearly radiogroup, featured middle card, tick lists and a ghost wordmark.",
    when: ["SaaS and product pricing pages"],
    file: "sections/PricingTiers.tsx",
    tags: ["pricing", "plans", "section", "billing toggle", "saas"],
    a11y: "Billing switch is a radiogroup with aria-checked; section labelled by its heading; ticks are aria-hidden.",
  },
  {
    slug: "wordmark-footer",
    title: "Wordmark footer",
    category: "Sections",
    summary: "Newsletter, link columns and a giant wordmark bleeding off the bottom edge, sized with container query units.",
    when: ["Studio, agency and brand sites", "Any footer that should close the page with presence"],
    file: "sections/WordmarkFooter.tsx",
    tags: ["footer", "wordmark", "newsletter", "container queries", "section"],
    a11y: "Labelled email input, nav landmarks per column; giant wordmark aria-hidden since the brand is in text.",
  },
  {
    slug: "contact-section",
    title: "Contact section",
    category: "Sections",
    summary: "Promise list, contact rows and a glass form with labelled fields, validation summary and success state.",
    when: ["Agency / freelancer / product contact pages"],
    file: "sections/ContactSection.tsx",
    tags: ["contact", "form", "validation", "section", "enquiry"],
    a11y: "Real <label>s, required fields, error summary in aria-live, success state with role=\"status\".",
  },
  {
    slug: "analytics-dashboard",
    title: "Analytics dashboard",
    category: "Screens",
    summary: "Full screen: sidebar, KPI tiles with sparklines, paired bar chart, arc dial, donut and orders table, all hand-drawn SVG.",
    when: ["Admin panels, SaaS dashboards, store analytics", "Reference for drawing charts without a library"],
    file: "screens/AnalyticsDashboard.tsx",
    tags: ["dashboard", "admin", "charts", "svg charts", "kpi", "table", "donut", "sparkline"],
    a11y: "Charts have role=\"img\" + text labels; data also present as text and a real <table> with scoped headers; aria-current on nav.",
  },
]

/** Sorted by category so the grid and prev/next follow the sidebar order. */
export const META: PatternMeta[] = ALL.map((p, i) => ({ p, i }))
  .sort((a, b) => CATEGORIES.indexOf(a.p.category) - CATEGORIES.indexOf(b.p.category) || a.i - b.i)
  .map(({ p }) => p)
